apiVersion: batch/v1
kind: Job
metadata:
  name: hotrod-load
  labels:
    app: hotrod-load
spec:
  template:
    metadata:
      labels:
        app: hotrod-load
    spec:
      containers:
      - image: hotrod-load:latest
        name: hotrod-load
      restartPolicy: Never
