---
apiVersion: v1
kind: Namespace
metadata:
  name: sick
---
apiVersion: v1
kind: Namespace
metadata:
  name: hotrod
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
