apiVersion: v1
kind: Service
metadata:
  name: hotrod-customer
  labels:
    app: hotrod
    hotrod-infra: customer-service
spec:
  ports:
  - name: customer-service
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    hotrod-infra: customer-pod
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hotrod-customer
  labels:
    app: hotrod
    hotrod-infra: customer-deployment
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hotrod
        hotrod-infra: customer-pod
    spec:
      containers:
      - image: rim:hotrod-kube-v1.0
        name: hotrod-customer
        command:
        - ./main
        args:
        - --jaeger-agent.host-port=localhost:6831
        - customer
        - --bind=0.0.0.0
        - $(CONFIG_DELAY)
        - $(CONFIG_MUTEX)
        ports:
        - containerPort: 8081
          protocol: TCP
        env:
        - name: CONFIG_DELAY
          valueFrom:
            configMapKeyRef:
              name: config-hotrod
              key: config-customer-delay
        - name: CONFIG_MUTEX
          valueFrom:
            configMapKeyRef:
              name: config-hotrod
              key: config-customer-mutex
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      - image: kaiju-agent:kaiju
        name: jaeger-agent
        command:
        - ./main
        env:
        - name: KAIJU_ADDRESS
          value: kaiju-traces.default:2042
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        args: 
        - --collector.host-port=jaeger-collector.default:14267
        - --processor.jaeger-compact.server-queue-size=500000
