apiVersion: v1
kind: Service
metadata:
  name: hotrod-driver
  labels:
    app: hotrod
    hotrod-infra: driver-service
spec:
  ports:
  - name: driver-service
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    hotrod-infra: driver-pod
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hotrod-driver
  labels:
    app: hotrod
    hotrod-infra: driver-deployment
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hotrod
        hotrod-infra: driver-pod
    spec:
      containers:
      - image: marioscrock/rim:hotrod-kube-v1.0
        name: hotrod-driver
        command:
        - ./main
        args:
        - --jaeger-agent.host-port=localhost:6831
        - driver
        - --bind=0.0.0.0
        - $(CONFIG_GET)
        - $(CONFIG_FIND)
        ports:
        - containerPort: 8082
          protocol: TCP
        env:
        - name: CONFIG_GET
          valueFrom:
            configMapKeyRef:
              name: config-hotrod
              key: config-driver-get
        - name: CONFIG_FIND
          valueFrom:
            configMapKeyRef:
              name: config-hotrod
              key: config-driver-find
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      - image: marioscrock/kaiju-agent:kaiju
        name: jaeger-agent
        command:
        - ./main
        env:
        - name: KAIJU_ADDRESS
          value: kaiju-traces.default:2042
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        args: 
        - --collector.host-port=jaeger-collector.default:14267
        - --processor.jaeger-compact.server-queue-size=500000
