apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kaiju-traces
  labels:
    app: kaiju
    kaiju-infra: kaiju-traces-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kaiju
        kaiju-infra: kaiju-traces-pod
    spec:
      containers:
      - image: marioscrock/kaiju:v1.0
        name: kaiju-traces
        command: ["java"]
        args: ["-jar","/usr/app/kaiju-0.0.1-SNAPSHOT-jar-with-dependencies.jar","-m traces","-rt 1min"]
        ports:
        - containerPort: 2042
          protocol: TCP
        - containerPort: 9278
          protocol: TCP
        env:
        - name: HL_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: config-hl
              key: address
        volumeMounts:
          - name: stmts-volume
            mountPath: /stmts
        env:
        - name: JAVA_OPTS
          value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
        resources:
          requests:
            memory: "250Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
        - name: stmts-volume
          configMap:
            name: kaiju-traces-stmts
---
apiVersion: v1
kind: Service
metadata:
  name: kaiju-traces
  labels:
    app: kaiju
    kaiju-infra: kaiju-traces-service
spec:
  ports:
  - name: kaiju-traces-tchannel
    port: 2042
    protocol: TCP
    targetPort: 2042
  - name: kaiju-traces-api
    port: 9278
    protocol: TCP
    targetPort: 9278
  selector:
    kaiju-infra: kaiju-traces-pod
  type: ClusterIP
