apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-controller-manager
  name: kube-controller-manager
spec:
  ports:
  - name: metrics
    port: 10252
    protocol: TCP
  selector:
    component: kube-controller-manager
