apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: coredns
  name: coredns
spec:
  ports:
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns