apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-scheduler
  name: kube-scheduler
spec:
  ports:
  - name: metrics
    port: 10251
    protocol: TCP
  selector:
    component: kube-scheduler